import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full bg-gray-100 flex items-center justify-center">
        <h1 className="text-4xl font-bold">
          hello and welcome to typescript course
        </h1>
      </main>
    </div>
  )
}
