import Head from 'next/head'

interface dataProps {
  title: string
  icon: string
}

export default function Home() {
  const data: dataProps[] = [
    { title: 'first div title', icon: 'X' },
    { title: 'second div title', icon: 'X' },
  ]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <button className="bg-[#1da1f2] text-white ...">
          Share on Twitter
        </button>
        <iframe
          className="w-full aspect-video ..."
          src="https://www.youtube.com/..."
        ></iframe>

        <div className="w-full bg-gray-00">
          <div className="py-32 flex justify-center items-center">
            {data.map((item, index) => {
              return (
                <div
                  className="w-[700px] h-[150px] ml-10 border border-yellow-600 border-l-yellow-600 border-l-[10px]"
                  key={index}
                >
                  <div className="flex items-center h-full">
                    <div className="w-20 h-20 bg-red-300 rounded-full flex items-center justify-center mx-3">
                      {item.icon}
                    </div>

                    <div className="">
                      <h1 className="text-2xl font-bold">{item.title}</h1>
                      <button>{item.title}</button>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </main>
    </div>
  )
}
