import Head from 'next/head'
// import { Button } from '../component/Button/Button'
// import Modal from '../component/Modal/Modal'

interface dataProps {
  title: string
  color: string
}

export default function Home() {
  // const data: dataProps[] = [
  //   { title: 'first title', color: 'red' },
  //   { title: 'second div title', color: 'black' },
  //   { title: 'div title the asdfas awefe', color: 'green' },
  //   { title: 'second div title', color: 'blue' },
  //   { title: 'second div title second div', color: 'gray' },
  // ]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="w-full">
          <div className="py-2 flex justify-center items-center">
            {data.map((item, index) => {
              return (
                <div
                  className="w-[160px] h-[260px] mx-1 border border-yellow-600 rounded-[20px] shadow"
                  style={{ backgroundColor: `${item.color}` }}
                  key={index}
                >
                  <div className="flex items-end h-full w-full p-5 shadow-inner">
                    <h1 className="text-bold text-lg text-white">
                      {item.title}
                    </h1>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </main>
    </div>
  )
}
